---

- name: Install database packages
  become: True
  package: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: Postgresql service running
  become: True
  service: name=postgresql state=started enabled=yes

- name: Create database
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_db:
    name: "{{ database_name }}"
    state: present
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Import vault variables
  include_vars: "{{ item }}"
  with_items:
    - "vault.yml"

- name: Grant user permission on database
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_user:
    db: "{{ database_name }}"
    name: "{{ database_user }}"
    password: "{{ database_user_password }}"
    encrypted: yes
    priv: ALL
    state: present

- name: Limit permissions on database user
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_user:
    name: "{{ database_user }}"
    role_attr_flags: "{{ item }}"
    state: present
  with_items:
    - "NOSUPERUSER"
    - "NOCREATEDB"

