---

- name: apt-get update
  become: True
  apt:
    update_cache: yes

- name: Update installed packages
  become: True
  apt: 
    upgrade: dist
  register: updates_applied

- name: Install common packages
  become: True
  package: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: UFW OpenSSH 
  become: True
  ufw: rule=limit port=ssh proto=tcp

- name: UFW HTTP Open
  become: True
  ufw: rule=allow port=80 proto=tcp

- name: UFW HTTPS Open
  become: True
  ufw: rule=allow port=443 proto=tcp

- name: UFW Deny Multicast
  become: True
  ufw: rule=deny from_ip=0.0.0.0 to_ip=224.0.0.1

- name: Disable UFW log to syslog
  become: True
  lineinfile:
    path: /etc/rsyslog.d/20-ufw.conf
    state: present
    regexp: '^& stop'
    line: "& stop"
  notify: restart rsyslog

- name: UFW Enabled
  become: True
  ufw: state=enabled

- name: sshd basic configuration
  become: True
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0600
    validate='/usr/sbin/sshd -T -f %s'
  notify: restart sshd

