---

- name: apt-get update
  become: True
  apt:
    update_cache: yes

- name: Update installed packages
  become: True
  apt: 
    upgrade: dist
  register: updates_applied

- name: Install common packages
  become: True
  package: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: UFW OpenSSH 
  become: True
  ufw: rule=limit port=ssh proto=tcp

- name: UFW HTTP Open
  become: True
  ufw: rule=allow port=80 proto=tcp

- name: UFW HTTPS Open
  become: True
  ufw: rule=allow port=443 proto=tcp

- name: UFW Deny Multicast
  become: True
  ufw: rule=deny from_ip=0.0.0.0 to_ip=224.0.0.1

- name: UFW Enabled
  become: True
  ufw: state=enabled

- name: sshd basic configuration
  become: True
  template: src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0600
    validate='/usr/sbin/sshd -T -f %s'
  notify: restart sshd

- name: Import application vault variables
  include_vars: "{{ item }}"
  with_items:
    - "vault.yml"

- name: Create Django User
  become: True
  user:
    name: "{{ django_user }}"
    state: present
    create_home: yes
    password: "{{ django_user_password }}"

- name: Django user .ssh directory
  become: True
  become_user: "{{ django_user }}"
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Django User Deploy Key
  become: yes
  become_user: "{{ django_user }}"
  copy:
    src: roles/application/files/deploy_key
    dest: ~/.ssh/id_rsa
    owner: "{{ django_user }}"
    mode: '0600'
    decrypt: yes

